# Generated by Django 4.2.7 on 2023-12-04 12:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gym_booking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='first_name',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='payment',
            name='last_name',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='gymmembership',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
