# Generated by Django 4.2.7 on 2023-12-11 18:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gym_booking', '0004_alter_gymmembership_user_alter_payment_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gymmembership',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gym_booking.customuser'),
        ),
    ]
